{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ib.secretName" . }}
  labels: {{- include "ib.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "ib.dbUrl" . | quote }}
{{- end }}
